//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Teams.App.KronosWfc.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class KronosResourceText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal KronosResourceText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Teams.App.KronosWfc.Resources.KronosResourceText", typeof(KronosResourceText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional request.
        /// </summary>
        internal static string AdditionalRequest {
            get {
                return ResourceManager.GetString("AdditionalRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add punch.
        /// </summary>
        internal static string AddPunch {
            get {
                return ResourceManager.GetString("AddPunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another Time Period.
        /// </summary>
        internal static string AnotherTimePeriod {
            get {
                return ResourceManager.GetString("AnotherTimePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        internal static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to approve swap request by employee.
        /// </summary>
        internal static string ApproveByEmp {
            get {
                return ResourceManager.GetString("ApproveByEmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to approve swap request by supervisor.
        /// </summary>
        internal static string ApproveBySupervisor {
            get {
                return ResourceManager.GetString("ApproveBySupervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        internal static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned to .
        /// </summary>
        internal static string AssignedTo {
            get {
                return ResourceManager.GetString("AssignedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned to you.
        /// </summary>
        internal static string AssignedToYou {
            get {
                return ResourceManager.GetString("AssignedToYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok, canceled. You can start over again or type &apos;help&apos; and discover available actions.
        /// </summary>
        internal static string CancelSwapShift {
            get {
                return ResourceManager.GetString("CancelSwapShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string CapsNext {
            get {
                return ResourceManager.GetString("CapsNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose an option..
        /// </summary>
        internal static string ChooseOption {
            get {
                return ResourceManager.GetString("ChooseOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to Log In.
        /// </summary>
        internal static string ClickLogin {
            get {
                return ResourceManager.GetString("ClickLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, I cannot understand you or I lost track of our conversation. Type &quot;help&quot; and discover available actions..
        /// </summary>
        internal static string CommandNotRecognized {
            get {
                return ResourceManager.GetString("CommandNotRecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select comment for the note..
        /// </summary>
        internal static string CommentSelectionValidation {
            get {
                return ResourceManager.GetString("CommentSelectionValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed requests.
        /// </summary>
        internal static string CompletedRequests {
            get {
                return ResourceManager.GetString("CompletedRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are performing punch with work rule transfer &lt;b&gt;{punchType}&lt;/b&gt; at &lt;b&gt;{datetime}&lt;/b&gt;. Is that correct?.
        /// </summary>
        internal static string ConfirmPunchWithTransfer {
            get {
                return ResourceManager.GetString("ConfirmPunchWithTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your time off request.
        /// </summary>
        internal static string ConfirmTimeoffRequest {
            get {
                return ResourceManager.GetString("ConfirmTimeoffRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact your administrator!!.
        /// </summary>
        internal static string ContactAdmin {
            get {
                return ResourceManager.GetString("ContactAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context or activity is missing..
        /// </summary>
        internal static string ContextMissing {
            get {
                return ResourceManager.GetString("ContextMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to current.
        /// </summary>
        internal static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Schedule Period.
        /// </summary>
        internal static string CurrentSchedulePeriod {
            get {
                return ResourceManager.GetString("CurrentSchedulePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Week Shifts.
        /// </summary>
        internal static string CurrentShift {
            get {
                return ResourceManager.GetString("CurrentShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Week.
        /// </summary>
        internal static string CurrentWeek {
            get {
                return ResourceManager.GetString("CurrentWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Range.
        /// </summary>
        internal static string DateRange {
            get {
                return ResourceManager.GetString("DateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        internal static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here is your schedule for the period - .
        /// </summary>
        internal static string DefaultSchedule {
            get {
                return ResourceManager.GetString("DefaultSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here are your shifts for - .
        /// </summary>
        internal static string DefaultShiftsText {
            get {
                return ResourceManager.GetString("DefaultShiftsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        internal static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since employee not found, notification is not sent..
        /// </summary>
        internal static string EmpNotFoundForNotification {
            get {
                return ResourceManager.GetString("EmpNotFoundForNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        internal static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End time.
        /// </summary>
        internal static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your comment.
        /// </summary>
        internal static string EnterComment {
            get {
                return ResourceManager.GetString("EnterComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered On.
        /// </summary>
        internal static string EnteredOn {
            get {
                return ResourceManager.GetString("EnteredOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a employee name.
        /// </summary>
        internal static string EnterEmployeeName {
            get {
                return ResourceManager.GetString("EnterEmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter an employee name or a part of it.
        /// </summary>
        internal static string EnterEmpName {
            get {
                return ResourceManager.GetString("EnterEmpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter end date.
        /// </summary>
        internal static string EnterEndDate {
            get {
                return ResourceManager.GetString("EnterEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter note (optional).
        /// </summary>
        internal static string EnterNote {
            get {
                return ResourceManager.GetString("EnterNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter start date.
        /// </summary>
        internal static string EnterStartDate {
            get {
                return ResourceManager.GetString("EnterStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the timeframe for shifts.
        /// </summary>
        internal static string EnterTimeframe {
            get {
                return ResourceManager.GetString("EnterTimeframe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the timeframe for schedule.
        /// </summary>
        internal static string EnterTimeframeForSchedule {
            get {
                return ResourceManager.GetString("EnterTimeframeForSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sfd.
        /// </summary>
        internal static string fdsf {
            get {
                return ResourceManager.GetString("fdsf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by.
        /// </summary>
        internal static string FilterBy {
            get {
                return ResourceManager.GetString("FilterBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Half Day.
        /// </summary>
        internal static string FirstHalfDay {
            get {
                return ResourceManager.GetString("FirstHalfDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For what end date?.
        /// </summary>
        internal static string ForEndDate {
            get {
                return ResourceManager.GetString("ForEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For what start date?.
        /// </summary>
        internal static string ForStartDate {
            get {
                return ResourceManager.GetString("ForStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from.
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Day.
        /// </summary>
        internal static string FullDay {
            get {
                return ResourceManager.GetString("FullDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hrs of.
        /// </summary>
        internal static string GenericHoursOfText {
            get {
                return ResourceManager.GetString("GenericHoursOfText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hrs.
        /// </summary>
        internal static string GenericHoursText {
            get {
                return ResourceManager.GetString("GenericHoursText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Half Day.
        /// </summary>
        internal static string HalfDay {
            get {
                return ResourceManager.GetString("HalfDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here are employees who are here today..
        /// </summary>
        internal static string HereAreEmpWhoAreHere {
            get {
                return ResourceManager.GetString("HereAreEmpWhoAreHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here are employees who are not here today..
        /// </summary>
        internal static string HereAreEmpWhoAreNotHere {
            get {
                return ResourceManager.GetString("HereAreEmpWhoAreNotHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        internal static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many hours did I work?.
        /// </summary>
        internal static string HoursWorked {
            get {
                return ResourceManager.GetString("HoursWorked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here are the worked hours for the period - from &lt;b&gt;{startDate}&lt;/b&gt; till &lt;b&gt;{endDate}&lt;/b&gt;..
        /// </summary>
        internal static string HoursWorkedDateRangeText {
            get {
                return ResourceManager.GetString("HoursWorkedDateRangeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here are the worked hours for the period - &lt;b&gt;{payPeriod}&lt;/b&gt;..
        /// </summary>
        internal static string HoursWorkedText {
            get {
                return ResourceManager.GetString("HoursWorkedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hrs worked.
        /// </summary>
        internal static string HrsWorkedTxt {
            get {
                return ResourceManager.GetString("HrsWorkedTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, I can&apos;t understand you. Please specify the date using format according to your locale policy..
        /// </summary>
        internal static string InvalidDate {
            get {
                return ResourceManager.GetString("InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last punch.
        /// </summary>
        internal static string LastPunch {
            get {
                return ResourceManager.GetString("LastPunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to log in first to continue..
        /// </summary>
        internal static string LoginToContinue {
            get {
                return ResourceManager.GetString("LoginToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here&apos;s the list of time off requests.
        /// </summary>
        internal static string ManagerViewTOR_InfoList {
            get {
                return ResourceManager.GetString("ManagerViewTOR_InfoList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee&apos;s Time Off Requests.
        /// </summary>
        internal static string ManagerViewTOR_Title {
            get {
                return ResourceManager.GetString("ManagerViewTOR_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show my schedule.
        /// </summary>
        internal static string MySchedule {
            get {
                return ResourceManager.GetString("MySchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string NextButton {
            get {
                return ResourceManager.GetString("NextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Schedule Period.
        /// </summary>
        internal static string NextSchedulePeriod {
            get {
                return ResourceManager.GetString("NextSchedulePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Week Shifts.
        /// </summary>
        internal static string NextShift {
            get {
                return ResourceManager.GetString("NextShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When is my next vacation?.
        /// </summary>
        internal static string NextVacation {
            get {
                return ResourceManager.GetString("NextVacation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nice to see you, {response.Name}! You can ask a question or type **help** and discover available actions..
        /// </summary>
        internal static string NiceToSeeYou {
            get {
                return ResourceManager.GetString("NiceToSeeYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (none).
        /// </summary>
        internal static string NoComment {
            get {
                return ResourceManager.GetString("NoComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, no data found. ☹.
        /// </summary>
        internal static string NoDataFound {
            get {
                return ResourceManager.GetString("NoDataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Employees found to swap shift.
        /// </summary>
        internal static string NoEmpForSwap {
            get {
                return ResourceManager.GetString("NoEmpForSwap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No employee was found by name {txt}.
        /// </summary>
        internal static string NoEmpFoundByName {
            get {
                return ResourceManager.GetString("NoEmpFoundByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No employees found!.
        /// </summary>
        internal static string NoEmployees {
            get {
                return ResourceManager.GetString("NoEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No employee was found who has clocked in today..
        /// </summary>
        internal static string NoEmployeesClockedToday {
            get {
                return ResourceManager.GetString("NoEmployeesClockedToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No employee was found who has not clocked in today..
        /// </summary>
        internal static string NoEmployeesNotClockedToday {
            get {
                return ResourceManager.GetString("NoEmployeesNotClockedToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No employees found on leave..
        /// </summary>
        internal static string NoEmployeesOnLeave {
            get {
                return ResourceManager.GetString("NoEmployeesOnLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Jobs found to swap.
        /// </summary>
        internal static string NoJobForSwap {
            get {
                return ResourceManager.GetString("NoJobForSwap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to none.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you do not have permission for this operation. ☹.
        /// </summary>
        internal static string NoPermission {
            get {
                return ResourceManager.GetString("NoPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No punches found for today.
        /// </summary>
        internal static string NoPunchesForToday {
            get {
                return ResourceManager.GetString("NoPunchesForToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No punches found for the period - **{payPeriod}**..
        /// </summary>
        internal static string NoPunchesFound {
            get {
                return ResourceManager.GetString("NoPunchesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No punches found for the period - from **{startDate}** till **{endDate}**..
        /// </summary>
        internal static string NoPunchesFoundDR {
            get {
                return ResourceManager.GetString("NoPunchesFoundDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No most recent transfers found..
        /// </summary>
        internal static string NoRecentTransfers {
            get {
                return ResourceManager.GetString("NoRecentTransfers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No schedule found.
        /// </summary>
        internal static string NoSchedule {
            get {
                return ResourceManager.GetString("NoSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No shifts were found.
        /// </summary>
        internal static string NoShifts {
            get {
                return ResourceManager.GetString("NoShifts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No shifts found for today.
        /// </summary>
        internal static string NoShiftsForToday {
            get {
                return ResourceManager.GetString("NoShiftsForToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no any time off requests for **{date}**..
        /// </summary>
        internal static string NoTimeOffRequests {
            get {
                return ResourceManager.GetString("NoTimeOffRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No vacation requests to show.
        /// </summary>
        internal static string NoVacationRequests {
            get {
                return ResourceManager.GetString("NoVacationRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no reported worked hours for the period - from &lt;b&gt;{startDate}&lt;/b&gt; till &lt;b&gt;{endDate}..
        /// </summary>
        internal static string NoWorkHoursDateRange {
            get {
                return ResourceManager.GetString("NoWorkHoursDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no reported worked hours for the period - &lt;b&gt;{payPeriod}&lt;/b&gt;..
        /// </summary>
        internal static string NoWorkHoursPeriod {
            get {
                return ResourceManager.GetString("NoWorkHoursPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees On Leave Today.
        /// </summary>
        internal static string OnLeave {
            get {
                return ResourceManager.GetString("OnLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees who are sick today.
        /// </summary>
        internal static string OnLeaveSick {
            get {
                return ResourceManager.GetString("OnLeaveSick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees who are on vacation today.
        /// </summary>
        internal static string OnLeaveVacation {
            get {
                return ResourceManager.GetString("OnLeaveVacation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;i&gt;Org job&lt;/i&gt; - {txt}&lt;br&gt;.
        /// </summary>
        internal static string OrgJobTxt {
            get {
                return ResourceManager.GetString("OrgJobTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay Code.
        /// </summary>
        internal static string PayCode {
            get {
                return ResourceManager.GetString("PayCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Week.
        /// </summary>
        internal static string PreviousWeek {
            get {
                return ResourceManager.GetString("PreviousWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary job.
        /// </summary>
        internal static string PrimaryJob {
            get {
                return ResourceManager.GetString("PrimaryJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary org.
        /// </summary>
        internal static string PrimaryOrg {
            get {
                return ResourceManager.GetString("PrimaryOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok, punch is canceled..
        /// </summary>
        internal static string PunchCancelled {
            get {
                return ResourceManager.GetString("PunchCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are performing punch at &lt;b&gt;{txt}&lt;/b&gt;. Is that correct?.
        /// </summary>
        internal static string PunchConfirmation {
            get {
                return ResourceManager.GetString("PunchConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done! Punch accepted on time &lt;b&gt;{datetime}.&lt;/b&gt;.
        /// </summary>
        internal static string PunchDone {
            get {
                return ResourceManager.GetString("PunchDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here are the punches for the period - &lt;b&gt;{payPeriod}&lt;/b&gt;..
        /// </summary>
        internal static string PunchesForPeriod {
            get {
                return ResourceManager.GetString("PunchesForPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here are the punches for the period - from &lt;b&gt;{startDate}&lt;/b&gt; till &lt;b&gt;{endDate}&lt;/b&gt;..
        /// </summary>
        internal static string PunchesForPeriodDR {
            get {
                return ResourceManager.GetString("PunchesForPeriodDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punch Time.
        /// </summary>
        internal static string PunchTime {
            get {
                return ResourceManager.GetString("PunchTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done! Punch with transfer work rule - &lt;b&gt;{workRuleName}&lt;/b&gt; accepted on time &lt;b&gt;{txt}.&lt;/b&gt;.
        /// </summary>
        internal static string PunchWithTransferDone {
            get {
                return ResourceManager.GetString("PunchWithTransferDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Transfers.
        /// </summary>
        internal static string RecentTransfers {
            get {
                return ResourceManager.GetString("RecentTransfers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refuse.
        /// </summary>
        internal static string Refuse {
            get {
                return ResourceManager.GetString("Refuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refuse swap request by employee.
        /// </summary>
        internal static string RefuseByEmp {
            get {
                return ResourceManager.GetString("RefuseByEmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refuse swap request by supervisor.
        /// </summary>
        internal static string RefuseBySupervisor {
            get {
                return ResourceManager.GetString("RefuseBySupervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refused.
        /// </summary>
        internal static string Refused {
            get {
                return ResourceManager.GetString("Refused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular: {regular} &lt;br&gt; Overtime: {overtime}.
        /// </summary>
        internal static string RegularOvertimeText {
            get {
                return ResourceManager.GetString("RegularOvertimeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested.
        /// </summary>
        internal static string Requested {
            get {
                return ResourceManager.GetString("Requested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to requested to swap shifts with you..
        /// </summary>
        internal static string RequestedShiftSwapWith {
            get {
                return ResourceManager.GetString("RequestedShiftSwapWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You requested to swap shift with .
        /// </summary>
        internal static string RequestedSwapShiftByYou {
            get {
                return ResourceManager.GetString("RequestedSwapShiftByYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to requested to swap shifts with.
        /// </summary>
        internal static string RequestSwapShiftWith {
            get {
                return ResourceManager.GetString("RequestSwapShiftWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request time off.
        /// </summary>
        internal static string RequestTimeOff {
            get {
                return ResourceManager.GetString("RequestTimeOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScheduleDateRange.
        /// </summary>
        internal static string ScheduleDateRange {
            get {
                return ResourceManager.GetString("ScheduleDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled Shifts.
        /// </summary>
        internal static string ScheduledShifts {
            get {
                return ResourceManager.GetString("ScheduledShifts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while fetching schedule.
        /// </summary>
        internal static string ScheduleError {
            get {
                return ResourceManager.GetString("ScheduleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select comment (optional).
        /// </summary>
        internal static string SelectComment {
            get {
                return ResourceManager.GetString("SelectComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select end date along with start date.
        /// </summary>
        internal static string SelectEndDate {
            get {
                return ResourceManager.GetString("SelectEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select start date along with end date.
        /// </summary>
        internal static string SelectStartDate {
            get {
                return ResourceManager.GetString("SelectStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift.
        /// </summary>
        internal static string Shift {
            get {
                return ResourceManager.GetString("Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shifts.
        /// </summary>
        internal static string Shifts {
            get {
                return ResourceManager.GetString("Shifts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing {first} - {last} of {totalEmp} absent employees.
        /// </summary>
        internal static string ShowAbsentEmployeesTxt {
            get {
                return ResourceManager.GetString("ShowAbsentEmployeesTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show completed requests.
        /// </summary>
        internal static string ShowCompletedRequests {
            get {
                return ResourceManager.GetString("ShowCompletedRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show history.
        /// </summary>
        internal static string ShowHistory {
            get {
                return ResourceManager.GetString("ShowHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show me my punches.
        /// </summary>
        internal static string ShowMyPunches {
            get {
                return ResourceManager.GetString("ShowMyPunches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing {first} - {last} of {totalEmp} present employees.
        /// </summary>
        internal static string ShowPresentEmployeesTxt {
            get {
                return ResourceManager.GetString("ShowPresentEmployeesTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Punch in.
        /// </summary>
        internal static string ShowPunchesCardPunchInColumnHeader {
            get {
                return ResourceManager.GetString("ShowPunchesCardPunchInColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punch out.
        /// </summary>
        internal static string ShowPunchesCardPunchOutColumnHeader {
            get {
                return ResourceManager.GetString("ShowPunchesCardPunchOutColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your timecard for the current period.
        /// </summary>
        internal static string ShowPunchesCardTitleText {
            get {
                return ResourceManager.GetString("ShowPunchesCardTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total hours:.
        /// </summary>
        internal static string ShowPunchesCardTotalHoursLabel {
            get {
                return ResourceManager.GetString("ShowPunchesCardTotalHoursLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule.
        /// </summary>
        internal static string ShowPunchesCardWorkRuleColumnHeader {
            get {
                return ResourceManager.GetString("ShowPunchesCardWorkRuleColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show schedule.
        /// </summary>
        internal static string ShowSchedule {
            get {
                return ResourceManager.GetString("ShowSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all time off requests.
        /// </summary>
        internal static string ShowTimeOffRequests {
            get {
                return ResourceManager.GetString("ShowTimeOffRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign-in required.
        /// </summary>
        internal static string SignInLabel {
            get {
                return ResourceManager.GetString("SignInLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been successfully authenticated..
        /// </summary>
        internal static string SignInSuccess {
            get {
                return ResourceManager.GetString("SignInSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        internal static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been signed out from Kronos..
        /// </summary>
        internal static string SignOutMessage {
            get {
                return ResourceManager.GetString("SignOutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        internal static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time.
        /// </summary>
        internal static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to submit punch without transfer at &lt;b&gt;{txt}&lt;/b&gt;?.
        /// </summary>
        internal static string SubmitPunchWithoutTransfer {
            get {
                return ResourceManager.GetString("SubmitPunchWithoutTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitted.
        /// </summary>
        internal static string Submitted {
            get {
                return ResourceManager.GetString("Submitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super User not configured correctly. Please contant administrator.
        /// </summary>
        internal static string SuperUserLoginError {
            get {
                return ResourceManager.GetString("SuperUserLoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since supervisor was not found, approval notification will not be sent..
        /// </summary>
        internal static string SupervisorNotFoundForNotification {
            get {
                return ResourceManager.GetString("SupervisorNotFoundForNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You {Status} {PayCode_Info} request..
        /// </summary>
        internal static string SupervisorTimeOffPostApprovalInfoText {
            get {
                return ResourceManager.GetString("SupervisorTimeOffPostApprovalInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor TOR list.
        /// </summary>
        internal static string SupervisorTORList {
            get {
                return ResourceManager.GetString("SupervisorTORList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show time off requests of employees.
        /// </summary>
        internal static string SupervisorTORListHelpButton {
            get {
                return ResourceManager.GetString("SupervisorTORListHelpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift swap request.
        /// </summary>
        internal static string SwapShiftConfirmTitle {
            get {
                return ResourceManager.GetString("SwapShiftConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need to swap a shift with your coworker? You can ask me \&quot;Swap Shift\&quot; and I will guide you through process..
        /// </summary>
        internal static string SwapShiftDesc {
            get {
                return ResourceManager.GetString("SwapShiftDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since employee requested to swap shift with could not be found, notification was not sent..
        /// </summary>
        internal static string SwapShiftEmpNotFoundToNotify {
            get {
                return ResourceManager.GetString("SwapShiftEmpNotFoundToNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create swap shift request.
        /// </summary>
        internal static string SwapShiftRequest {
            get {
                return ResourceManager.GetString("SwapShiftRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully submitted swap shift request..
        /// </summary>
        internal static string SwapShiftSubmitSuccess {
            get {
                return ResourceManager.GetString("SwapShiftSubmitSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I need to take a sick day.
        /// </summary>
        internal static string TakeSickDay {
            get {
                return ResourceManager.GetString("TakeSickDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing {First} - {Last} of {Total} employees&apos; for the {Payperiod}.
        /// </summary>
        internal static string TeamOTCardTitle {
            get {
                return ResourceManager.GetString("TeamOTCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here are team overtimes for the period - &lt;b&gt;{PayPeriod}&lt;/b&gt;.
        /// </summary>
        internal static string TeamOvertimeDataFound {
            get {
                return ResourceManager.GetString("TeamOvertimeDataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here are team overtimes for the period - from &lt;b&gt;{StartDate}&lt;/b&gt; till &lt;b&gt;{EndDate}.&lt;/b&gt;.
        /// </summary>
        internal static string TeamOvertimeDataFoundDateRange {
            get {
                return ResourceManager.GetString("TeamOvertimeDataFoundDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No overtimes found for the period - &lt;b&gt;{PayPeriod}&lt;/b&gt;.
        /// </summary>
        internal static string TeamOvertimeNoDataFound {
            get {
                return ResourceManager.GetString("TeamOvertimeNoDataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No overtimes found for the period - from &lt;b&gt;{StartDate}&lt;/b&gt; till &lt;b&gt;{EndDate}.&lt;/b&gt;.
        /// </summary>
        internal static string TeamOvertimeNoDataFoundDateRange {
            get {
                return ResourceManager.GetString("TeamOvertimeNoDataFoundDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Overtimes (hours).
        /// </summary>
        internal static string TeamOvertimesTitle {
            get {
                return ResourceManager.GetString("TeamOvertimesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to till.
        /// </summary>
        internal static string Till {
            get {
                return ResourceManager.GetString("Till", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You {status} {paycode} request..
        /// </summary>
        internal static string TimeOffApprovalReply {
            get {
                return ResourceManager.GetString("TimeOffApprovalReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View your time off balances and create a time off request. You can ask \&quot;How much vacation balance do I have?\&quot; or \&quot;Create time off\&quot; and I will guide you through the process step-by-step..
        /// </summary>
        internal static string TimeOffDesc {
            get {
                return ResourceManager.GetString("TimeOffDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Supervisor} has {Status} your {Paycode_Info} request!.
        /// </summary>
        internal static string TimeOffEmployeeNotificationInfoText {
            get {
                return ResourceManager.GetString("TimeOffEmployeeNotificationInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create time off request.
        /// </summary>
        internal static string TimeOffRequest {
            get {
                return ResourceManager.GetString("TimeOffRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request overlaps an existing pay code edit for the same pay code..
        /// </summary>
        internal static string TimeOffRequestOverlap {
            get {
                return ResourceManager.GetString("TimeOffRequestOverlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully submitted your {Paycode_Info} request!.
        /// </summary>
        internal static string TimeOffRequestSuccessInfoText {
            get {
                return ResourceManager.GetString("TimeOffRequestSuccessInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time off request.
        /// </summary>
        internal static string TimeOffRequstText {
            get {
                return ResourceManager.GetString("TimeOffRequstText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need to request some time off?.
        /// </summary>
        internal static string TimeOffTour {
            get {
                return ResourceManager.GetString("TimeOffTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Period.
        /// </summary>
        internal static string TimePeriod {
            get {
                return ResourceManager.GetString("TimePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Today**.
        /// </summary>
        internal static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string TodayTxt {
            get {
                return ResourceManager.GetString("TodayTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to swap shifts with you..
        /// </summary>
        internal static string ToSwapWithYou {
            get {
                return ResourceManager.GetString("ToSwapWithYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Total Worked - {totalWorked} hours&lt;/b&gt;.
        /// </summary>
        internal static string TotalHourdWorked {
            get {
                return ResourceManager.GetString("TotalHourdWorked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total hours worked.
        /// </summary>
        internal static string TotalhrsWorkedTxt {
            get {
                return ResourceManager.GetString("TotalhrsWorkedTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {allHours} hrs of {assignedHours} hrs.
        /// </summary>
        internal static string TotalhrsWorkedTxtVal {
            get {
                return ResourceManager.GetString("TotalhrsWorkedTxtVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok, transfer is canceled..
        /// </summary>
        internal static string TransferCanceled {
            get {
                return ResourceManager.GetString("TransferCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;i&gt;Transfer&lt;/i&gt; - {txt}&lt;br&gt;.
        /// </summary>
        internal static string TransferTxt {
            get {
                return ResourceManager.GetString("TransferTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of time off.
        /// </summary>
        internal static string TypeOfTimeoff {
            get {
                return ResourceManager.GetString("TypeOfTimeoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to proceed. Try again.
        /// </summary>
        internal static string UnableToProceed {
            get {
                return ResourceManager.GetString("UnableToProceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need to view your upcoming schedule?.
        /// </summary>
        internal static string UpcomingSchedTour {
            get {
                return ResourceManager.GetString("UpcomingSchedTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My upcoming shifts.
        /// </summary>
        internal static string UpcomingShifts {
            get {
                return ResourceManager.GetString("UpcomingShifts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View your schedule and upcoming shifts. You can ask me \&quot;What is my schedule?\&quot;, \&quot;View my upcoming shifts\&quot;, \&quot;Punches\&quot; and I will guide you through the process step-by-step..
        /// </summary>
        internal static string UpcomingShiftsDesc {
            get {
                return ResourceManager.GetString("UpcomingShiftsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        internal static string Updated {
            get {
                return ResourceManager.GetString("Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVAILABLE.
        /// </summary>
        internal static string VacationBalanceCardAvailableText {
            get {
                return ResourceManager.GetString("VacationBalanceCardAvailableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Grants.
        /// </summary>
        internal static string VacationBalanceCardPendingGrantsLabel {
            get {
                return ResourceManager.GetString("VacationBalanceCardPendingGrantsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal leave.
        /// </summary>
        internal static string VacationBalanceCardPersonalLabel {
            get {
                return ResourceManager.GetString("VacationBalanceCardPersonalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned Takings.
        /// </summary>
        internal static string VacationBalanceCardPlannedTakingsLabel {
            get {
                return ResourceManager.GetString("VacationBalanceCardPlannedTakingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probation Hours.
        /// </summary>
        internal static string VacationBalanceCardProbationHoursLabel {
            get {
                return ResourceManager.GetString("VacationBalanceCardProbationHoursLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCK.
        /// </summary>
        internal static string VacationBalanceCardSCKLabel {
            get {
                return ResourceManager.GetString("VacationBalanceCardSCKLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here is the summary of your available vacation balance as of.
        /// </summary>
        internal static string VacationBalanceCardSubtitleText {
            get {
                return ResourceManager.GetString("VacationBalanceCardSubtitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacation Balance.
        /// </summary>
        internal static string VacationBalanceCardTitleText {
            get {
                return ResourceManager.GetString("VacationBalanceCardTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vested Hours.
        /// </summary>
        internal static string VacationBalanceCardVestedHoursLabel {
            get {
                return ResourceManager.GetString("VacationBalanceCardVestedHoursLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal.
        /// </summary>
        internal static string VacationBalanceCodePersonal {
            get {
                return ResourceManager.GetString("VacationBalanceCodePersonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sick.
        /// </summary>
        internal static string VacationBalanceCodeSick {
            get {
                return ResourceManager.GetString("VacationBalanceCodeSick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacation.
        /// </summary>
        internal static string VacationBalanceCodeVacation {
            get {
                return ResourceManager.GetString("VacationBalanceCodeVacation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many vacation hours do I have?.
        /// </summary>
        internal static string VacationHours {
            get {
                return ResourceManager.GetString("VacationHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Hi, I&apos;m Kronos WFC Bot and I can help you manage your shifts, time off requests, show your schedule, overtime hours.&lt;br&gt; &lt;br&gt;Here are some of the things that I can do:
        ///                  &lt;br&gt;&lt;ul&gt;&lt;li&gt;When am I working this week?&lt;/li&gt;&lt;li&gt;When is my next vacation?&lt;/li&gt;
        ///                  &lt;li&gt;what is my Vacation Balance?&lt;/li&gt;&lt;/ul&gt;
        ///                  &lt;br&gt;To see more available options, type help..
        /// </summary>
        internal static string WelcomeKronosText {
            get {
                return ResourceManager.GetString("WelcomeKronosText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where is someone today?.
        /// </summary>
        internal static string WhereIsSomeone {
            get {
                return ResourceManager.GetString("WhereIsSomeone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who is approaching overtime?.
        /// </summary>
        internal static string WhoIsApproachingOT {
            get {
                return ResourceManager.GetString("WhoIsApproachingOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who is here?.
        /// </summary>
        internal static string WhoIsHere {
            get {
                return ResourceManager.GetString("WhoIsHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who is not here?.
        /// </summary>
        internal static string WhoIsNotHere {
            get {
                return ResourceManager.GetString("WhoIsNotHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worked Shifts - {grandTotal} hours&lt;br&gt;.
        /// </summary>
        internal static string WorkedShiftsText {
            get {
                return ResourceManager.GetString("WorkedShiftsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Rule Transfer.
        /// </summary>
        internal static string WorkRuleTransfer {
            get {
                return ResourceManager.GetString("WorkRuleTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to work rule transfer.
        /// </summary>
        internal static string WorkRuleTransferPunch {
            get {
                return ResourceManager.GetString("WorkRuleTransferPunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;i&gt;Work rule&lt;/i&gt; - {txt}&lt;br&gt;.
        /// </summary>
        internal static string WorkRuleTxt {
            get {
                return ResourceManager.GetString("WorkRuleTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You approved swap shift request..
        /// </summary>
        internal static string YouApprovedSwapShiftRequest {
            get {
                return ResourceManager.GetString("YouApprovedSwapShiftRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You refused swap shift request..
        /// </summary>
        internal static string YouRefusedSwapShiftRequest {
            get {
                return ResourceManager.GetString("YouRefusedSwapShiftRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Schedule.
        /// </summary>
        internal static string YourScheduleTitle {
            get {
                return ResourceManager.GetString("YourScheduleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Shifts.
        /// </summary>
        internal static string YourShiftsTitle {
            get {
                return ResourceManager.GetString("YourShiftsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your vacation requests.
        /// </summary>
        internal static string YourVacationRequests {
            get {
                return ResourceManager.GetString("YourVacationRequests", resourceCulture);
            }
        }
    }
}
