//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Teams.App.KronosWfc.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class KronosCommand {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal KronosCommand() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Teams.App.KronosWfc.Resources.KronosCommand", typeof(KronosCommand).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add punch.
        /// </summary>
        internal static string AddPunch {
            get {
                return ResourceManager.GetString("AddPunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to current schedule period.
        /// </summary>
        internal static string CurrentSchedulePeriod {
            get {
                return ResourceManager.GetString("CurrentSchedulePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show time off requests of employees.
        /// </summary>
        internal static string EmployeeTORList {
            get {
                return ResourceManager.GetString("EmployeeTORList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next schedule period.
        /// </summary>
        internal static string NextSchedulePeriod {
            get {
                return ResourceManager.GetString("NextSchedulePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to when is my next vacation?.
        /// </summary>
        internal static string NextVacation {
            get {
                return ResourceManager.GetString("NextVacation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to punch.
        /// </summary>
        internal static string Punch {
            get {
                return ResourceManager.GetString("Punch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to transfer.
        /// </summary>
        internal static string RecentTransferPunch {
            get {
                return ResourceManager.GetString("RecentTransferPunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show my schedule.
        /// </summary>
        internal static string ShowSchedule {
            get {
                return ResourceManager.GetString("ShowSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to signout.
        /// </summary>
        internal static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my upcoming shifts.
        /// </summary>
        internal static string UpcomingShifts {
            get {
                return ResourceManager.GetString("UpcomingShifts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vacation.
        /// </summary>
        internal static string Vacation {
            get {
                return ResourceManager.GetString("Vacation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to how many vacation hours do i have?.
        /// </summary>
        internal static string VacationBalance {
            get {
                return ResourceManager.GetString("VacationBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to work rule transfer.
        /// </summary>
        internal static string WorkRuleTransferPunch {
            get {
                return ResourceManager.GetString("WorkRuleTransferPunch", resourceCulture);
            }
        }
    }
}
